import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { basename, dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const componentsDirectory = join(root, 'src', 'components')
const indexPath = join(componentsDirectory, 'index.js')
const outputPath = join(root, 'dist', 'components.d.ts')

const componentEntries = await readdir(componentsDirectory, { withFileTypes: true })
const declarationPaths = []
for (let i = 0; i < componentEntries.length; i++) {
  const entry = componentEntries[i]
  if (!entry.isDirectory()) {
    continue
  }

  const path = join(componentsDirectory, entry.name, `${entry.name}.d.ts`)
  const directoryEntries = await readdir(join(componentsDirectory, entry.name))
  if (directoryEntries.includes(`${entry.name}.d.ts`)) {
    declarationPaths.push(path)
  }
}

const indexSource = await readFile(indexPath, 'utf8')
const orderedNames = []
const importPattern = /from '\.\/([^/]+)\/[^']+\.js'/g
for (let match = importPattern.exec(indexSource); match; match = importPattern.exec(indexSource)) {
  if (!orderedNames.includes(match[1])) {
    orderedNames.push(match[1])
  }
}

const order = new Map()
for (let i = 0; i < orderedNames.length; i++) {
  order.set(orderedNames[i], i)
}

declarationPaths.sort((left, right) => {
  const leftName = basename(dirname(left))
  const rightName = basename(dirname(right))
  const leftOrder = order.has(leftName) ? order.get(leftName) : Number.MAX_SAFE_INTEGER
  const rightOrder = order.has(rightName) ? order.get(rightName) : Number.MAX_SAFE_INTEGER
  return leftOrder - rightOrder || leftName.localeCompare(rightName)
})

const declarations = []
const exportedTypes = new Set()
for (let i = 0; i < declarationPaths.length; i++) {
  const path = declarationPaths[i]
  const source = (await readFile(path, 'utf8')).trim()
  const displayPath = relative(root, path)

  if (/^\s*import\s/m.test(source) || /^\s*export\s+(?:\*|\{)[^\n]*\sfrom\s/m.test(source)) {
    throw new Error(`${displayPath} must not import or re-export declarations from another component`)
  }

  const typePattern = /^export type (\w+)/gm
  for (let match = typePattern.exec(source); match; match = typePattern.exec(source)) {
    if (exportedTypes.has(match[1])) {
      throw new Error(`Duplicate exported type ${match[1]} in ${displayPath}`)
    }
    exportedTypes.add(match[1])
  }

  const componentName = basename(dirname(path))
  const section = `/* ==========================================================================
 * Component: ${componentName}
 * Source: ${displayPath}
 * ========================================================================== */`
  declarations.push(`${section}

${source}`)
}

const header = `/**
 * Generated by \`make types\` from the declaration files beside each component.
 * Edit \`src/components/[Component]/[Component].d.ts\`, not this file.
 */`

await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, `${header}\n\n${declarations.join('\n\n')}\n`)
console.log(`Built ${relative(root, outputPath)} from ${declarationPaths.length} component declaration files.`)
